In [1]:
import pandas as pd
import numpy as np

1. Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [2]:
array_2D_1 = np.random.randint(34, 99, size = (4,3))
array_2D_1

array([[66, 60, 79],
       [46, 58, 86],
       [35, 62, 54],
       [84, 57, 95]])

2. Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

In [ ]:
# Las listas para crear los arrays son las siguientes
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [6]:
array_1D_lista1 = np.array(lista1)
array_1D_lista1 

array([34, 56, 71, 98, 10])

In [7]:
array_2D_lista2 = np.array(lista2)
array_2D_lista2

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

In [8]:
type(array_2D_lista2)

numpy.ndarray

3. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

- El primer elemento.

- Lo elementos que están en posición impar.

- Los cuatro primeros elementos.

- Los últimos tres elementos.

- Los elementos entre el 4 y el 8 (incluido).

In [9]:
array_1D_arange = np.arange(51)
array_1D_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
# el 1er elemento
array_1D_arange[0]

0

In [ ]:
# elementos POSICIÓN impar (lenguaje python)
array_1D_arange[1: :2] 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
# POSICIÓN impar (lenguaje humano))
array_1D_arange[: :2] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [17]:
# los 4 primeros elementos
array_1D_arange[:4]

array([0, 1, 2, 3])

In [20]:
# los últimos 3 elementos
array_1D_arange[-3:]

array([48, 49, 50])

In [ ]:
array_1D_arange[:-3] # te quita los últimos tres

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [24]:
# los elementos entre el 4 y el 8 incluido
array_1D_arange[4:9]

array([4, 5, 6, 7, 8])

4. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

- La primera fila y todas las columnas.

- Todas las filas pares.

- La primera columna y todas las filas.

In [25]:
array_2D_ej4 = np.random.randint(20, 84, size = (4,5))
array_2D_ej4

array([[82, 22, 65, 41, 49],
       [38, 66, 44, 82, 67],
       [47, 67, 64, 82, 73],
       [21, 39, 40, 65, 65]])

In [31]:
# 1a fila y todas las columnas
array_2D_ej4[0,:]

array([82, 22, 65, 41, 49])

In [ ]:
# todas las filas pares  --> lenguaje humano
array_2D_ej4[:4:2,:]

array([[82, 22, 65, 41, 49],
       [47, 67, 64, 82, 73]])

In [ ]:
array_2D_ej4[1:4:2,:] # todas las filas pares  --> lenguaje python

array([[38, 66, 44, 82, 67],
       [21, 39, 40, 65, 65]])

In [47]:
# la 1a columna y TODAS las filas
array_2D_ej4[:,0]

array([82, 38, 47, 21])

5. Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

- Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

- Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [49]:
array_2D_ej5 = np.random.randint(0, 51, size = (4,5))
array_2D_ej5

array([[20,  9, 25, 40, 42],
       [38, 43, 23, 38, 26],
       [ 9, 27, 29, 21,  3],
       [ 1,  9,  4,  9,  0]])

In [ ]:
# mascara valores mayores 30 y menor a 10
mascara = np.where(array_2D_ej5 > 30, np.where(array_2D_ej5 < 10, "objectivo", "no es mi objetivo"))
mascara

ValueError: either both or neither of x and y should be given