In [3]:
import pandas as pd
import numpy as np

1. Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [4]:
array_2D_1 = np.random.randint(34, 99, size = (4,3))
array_2D_1

array([[55, 92, 74],
       [36, 86, 86],
       [46, 55, 54],
       [53, 83, 65]])

2. Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

In [5]:
# Las listas para crear los arrays son las siguientes
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [6]:
array_1D_lista1 = np.array(lista1)
array_1D_lista1 

array([34, 56, 71, 98, 10])

In [7]:
array_2D_lista2 = np.array(lista2)
array_2D_lista2

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])

In [8]:
type(array_2D_lista2)

numpy.ndarray

3. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

- El primer elemento.

- Lo elementos que están en posición impar.

- Los cuatro primeros elementos.

- Los últimos tres elementos.

- Los elementos entre el 4 y el 8 (incluido).

In [9]:
array_1D_arange = np.arange(51)
array_1D_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
# el 1er elemento
array_1D_arange[0]

0

In [11]:
# elementos POSICIÓN impar (lenguaje python)
array_1D_arange[1: :2] 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [12]:
# POSICIÓN impar (lenguaje humano))
array_1D_arange[: :2] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [13]:
# los 4 primeros elementos
array_1D_arange[:4]

array([0, 1, 2, 3])

In [14]:
# los últimos 3 elementos
array_1D_arange[-3:]

array([48, 49, 50])

In [15]:
array_1D_arange[:-3] # te quita los últimos tres

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [16]:
# los elementos entre el 4 y el 8 incluido
array_1D_arange[4:9]

array([4, 5, 6, 7, 8])

4. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

- La primera fila y todas las columnas.

- Todas las filas pares.

- La primera columna y todas las filas.

In [17]:
array_2D_ej4 = np.random.randint(20, 84, size = (4,5))
array_2D_ej4

array([[52, 38, 36, 83, 35],
       [35, 77, 29, 52, 52],
       [37, 38, 56, 72, 52],
       [23, 78, 77, 60, 78]])

In [18]:
# 1a fila y todas las columnas
array_2D_ej4[0,:]

array([52, 38, 36, 83, 35])

In [19]:
# todas las filas pares  --> lenguaje humano
array_2D_ej4[:4:2,:]

array([[52, 38, 36, 83, 35],
       [37, 38, 56, 72, 52]])

In [20]:
array_2D_ej4[1:4:2,:] # todas las filas pares  --> lenguaje python

array([[35, 77, 29, 52, 52],
       [23, 78, 77, 60, 78]])

5. Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

- Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

- Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [21]:
# la 1a columna y TODAS las filas
array_2D_ej4[:,0]

array([52, 35, 37, 23])

In [22]:
array_2D_ej5 = np.random.randint(0, 51, size = (4,5))
array_2D_ej5

array([[11, 33, 32, 26, 21],
       [ 2,  2, 39,  4, 13],
       [39, 30, 11, 23, 37],
       [ 1, 18, 34, 13, 45]])

In [29]:
# mascara valores mayores 30 y menores a 10
mascara = (array_2D_ej5 > 30) | (array_2D_ej5 < 10)

In [31]:
resultado = np.where(mascara, "objetivo", "no es mi objetivo")
print(resultado)

[['no es mi objetivo' 'objetivo' 'objetivo' 'no es mi objetivo'
  'no es mi objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']
 ['objetivo' 'no es mi objetivo' 'no es mi objetivo' 'no es mi objetivo'
  'objetivo']
 ['objetivo' 'no es mi objetivo' 'objetivo' 'no es mi objetivo'
  'objetivo']]


In [32]:
# array multiplicado por el escalar 10
escalar = 10
array_2D_ej5 * escalar

array([[110, 330, 320, 260, 210],
       [ 20,  20, 390,  40, 130],
       [390, 300, 110, 230, 370],
       [ 10, 180, 340, 130, 450]])


6. Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

Suma el primer array con el segundo.

Aplicar la potencia para el primer array elevado al segundo.

In [33]:
array_2D_ej6 = np.random.randint(51, 101, size = (4,5))
array_2D_ej6

array([[ 92,  77,  74,  80,  91],
       [ 77,  55,  91,  74,  65],
       [ 84,  62,  84,  92,  65],
       [ 99,  81, 100,  79,  85]])

In [34]:
# suma el primer array con el segundo
array_2D_ej5 + array_2D_ej6

array([[103, 110, 106, 106, 112],
       [ 79,  57, 130,  78,  78],
       [123,  92,  95, 115, 102],
       [100,  99, 134,  92, 130]])

In [37]:
# aplicar la potencia al primer array elevado al segundo
potencia = np.power(array_2D_ej5, array_2D_ej6)
potencia

array([[ 2030249621719054417, -2953674410420289119,                    0,
                           0, -1534045714529295923],
       [                   0,    36028797018963968, -5498489056002644361,
                           0, -5058422884668523251],
       [-4548275446437964191,  4611686018427387904,  4323319620982420209,
        -1787182201297638943,  4773011433147663141],
       [                   1,                    0,                    0,
        -1485145929550239483, -4334167754899048643]])


7. Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

Calcula:

La media de los elementos

La media de las columnas y redondéalo a dos decimales

El valor máximo de cada fila

El valor mínimo de cada fila

Hay algun valor que sea mayor que 90 en tu array

Donde los podemos encontrar, cuáles son sus índices

Ordena el array de mayor a menor

In [38]:
array_2D_ej7 = np.random.randint(0, 101, size = (4,5))
array_2D_ej7

array([[33, 64, 37, 95, 50],
       [60, 10, 74, 75, 62],
       [ 0,  0,  6, 86, 42],
       [14, 24, 16, 95,  2]])

In [39]:
# la media de los elementos
np.mean(array_2D_ej7)

42.25

In [42]:
# la media por columna y redondealo a 2 decimales
(array_2D_ej7.mean(axis=0)).round(decimals=2)

array([26.75, 24.5 , 33.25, 87.75, 39.  ])

In [44]:
# el valor maximo de cada fila
array_2D_ej7.max(axis=1)

array([95, 75, 86, 95])

In [45]:
# el valor minimo de cada fila
array_2D_ej7.min(axis=1)

array([33, 10,  0,  2])

In [ ]:
# valor mayor a 90 en el array y sus indices
indices_mayores = np.where(array_2D_ej7 > 90)
print("Índices donde los valores son mayores a 90:", indices_mayores)

Índices donde los valores son mayores a 90: (array([0, 3]), array([3, 3]))


In [51]:
# ordenar el array de mayor a menor
ordenado = np.sort(array_2D_ej7)
ordenado[:, ::-1]

array([[95, 64, 50, 37, 33],
       [75, 74, 62, 60, 10],
       [86, 42,  6,  0,  0],
       [95, 24, 16, 14,  2]])